mybatis:
  type-aliases-package: "com.funi.muyq.angular.zorroserver.po,com.funi.muyq.angular.zorroserver.vo"
  mapper-locations: "classpath:config/mapper/*.xml"
  config-location: "classpath:config/spring/mybatis-config.xml"
spring:
  datasource:
    url: "jdbc:mysql://45.77.6.219:3306/cas?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "MYQ@hot520"
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    com:
      funi:
        muyq:
          angular:
            zorroserver:
              mapper: debug
server:
  port: @server.port@
  servlet:
    context-path: @server.path@